package com.easymed.droplet;

import java.io.IOException;
import java.util.ArrayList;

import javax.servlet.ServletException;
import javax.servlet.ServletOutputStream;

import atg.repository.MutableRepository;
import atg.repository.RepositoryException;
import atg.servlet.DynamoHttpServletRequest;
import atg.servlet.DynamoHttpServletResponse;
import atg.servlet.DynamoServlet;

public class test extends DynamoServlet{
	
	
	MutableRepository testRepo;
	MutableRepository blogRepo;

	
	public MutableRepository getBlogRepo() {
		return blogRepo;
	}
	public void setBlogRepo(MutableRepository blogRepo) {
		this.blogRepo = blogRepo;
	}
	public MutableRepository getTestRepo() {
		return testRepo;
	}
	public void setTestRepo(MutableRepository testRepo) {
		this.testRepo = testRepo;
	}
	public test () {}
	  public void service (DynamoHttpServletRequest request,
	                       DynamoHttpServletResponse response)
	       throws ServletException, IOException
	  {
	    ServletOutputStream out = response.getOutputStream ();
	    System.out.println("hrrrefesfdsf");
	    String name = request.getParameter ("name" +
	    		"");
	    out.println ("<h1>I am generated by a java object.  "+name+" </h1>");
	    request.setParameter ("goods", "Golf Balls");
	    request.serviceParameter ("openname", request, response);
	    
	    ArrayList<String> ar = new ArrayList<String>();
	    ar.add("Ganesan");
	    ar.add("Anand");
	    ar.add("Ravi");
	    request.setParameter ("testList", ar);
	    
	    try {
			MutableRepository murep=(MutableRepository) getBlogRepo().getItem("1","test");
	    	//MutableRepository item = (MutableRepository) getBlogRepo()
		//	.getItem("1", "blog");
			System.out.println(murep);
		} catch (Exception e) {
			System.out.println("---------------------------------------------");
			e.printStackTrace();
		}
	    
	  }

}
